=== mechno14/PB138-project/scheme.xsd
<?xml version="1.0"?>

<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

    <xsd:element name="videoLibrary" >
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="categories" type="categoriesList" />
            </xsd:sequence>
        </xsd:complexType>
        <xsd:key name="mediumIdKey">
            <xsd:selector xpath="categories/category/medium" />
            <xsd:field xpath="@id" />
        </xsd:key>
    </xsd:element>

    <xsd:complexType name="categoriesList">
        <xsd:sequence>
            <xsd:element name="category" type="categoryType" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="categoryType">
        <xsd:sequence>
            <xsd:element name="medium" type="mediumType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="nonEmptyString" use="required"/>
     </xsd:complexType>

    <xsd:simpleType name="nonEmptyString">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="mediumType">
        <xsd:all>
            <xsd:element name="mediumType" type="typeEnum" />
            <xsd:element name="name" type="nonEmptyString" /> <!-- mozno specialiovat aby neobsahovalo divne znaky -->
            <xsd:element name="length" type="lengthType" />
            <xsd:element name="actors" type="listOfActors" minOccurs="0"/>
            <xsd:element name="genres" type="genresType" minOccurs="0"/>
            <xsd:element name="releaseYear" type="xsd:nonNegativeInteger" />
        </xsd:all>
        <xsd:attribute name="id" type="xsd:integer" use="required" />
    </xsd:complexType>

    <xsd:simpleType name="typeEnum">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="VHS" />
            <xsd:enumeration value="DVD" />
            <xsd:enumeration value="USB" />
            <xsd:enumeration value="memory card" />
            <xsd:enumeration value="other" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="lengthType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([1-9][0-9]*)|unknown"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="listOfActors">
        <xsd:sequence>
            <xsd:element name="actor" type="nameString" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="nameString">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[\p{Lu}][\p{Ll}]+(\s[\p{Lu}][\p{Ll}]+)(\s[\p{Lu}][\p{Ll}]+)*"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="genresType">
        <xsd:sequence>
            <xsd:element name="genre" type="nonEmptyString" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>



</xsd:schema>

=== mechno14/PB138-project/database.xml
<?xml version="1.0" encoding="UTF-8"?>

<videoLibrary
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='scheme.xsd'>

    <categories>
        <category name="Movies" price="5.90">
            <medium id="1">
                <mediumType>DVD</mediumType>
                <name>Shrek</name>
                <length>90</length>
                <actors>
                    <actor>Mike Myers</actor>
                    <actor>Eddie Murphy</actor>
                    <actor>Cameron Diaz</actor>
                </actors>
                <status>available</status>
                <genres>
                    <genre>Animated</genre>
                    <genre>Adventure</genre>
                    <genre>Comedy</genre>
                </genres>
                <releaseYear>2001</releaseYear>
            </medium>
            <medium id="2">
                <mediumType>VHS</mediumType>
                <name>Lemonade Joe</name>
                <length>84</length>
                <actors>
                    <actor>Karel Fiala</actor>
                    <actor>Rudolf Deyl</actor>
                    <actor>Miloš Kopecký</actor>
                </actors>
                <status>broken</status>
                <genres>
                    <genre>Adventure</genre>
                    <genre>Comedy</genre>
                    <genre>Musical</genre>
                </genres>
                <releaseYear>1964</releaseYear>
            </medium>
            <medium id="3">
                <mediumType>USB</mediumType>
                <name>Sex and the City</name>
                <length>145</length>
                <actors>
                    <actor>Sarah Jessica Parker</actor>
                    <actor>Kim Cattrall</actor>
                    <actor>Cynthia Nixon</actor>
                </actors>
                <status>lost</status>
                <genres>
                    <genre>Comedy</genre>
                    <genre>Drama</genre>
                    <genre>Romance</genre>
                </genres>
                <releaseYear>2008</releaseYear>
            </medium>
        </category>
        <category name="Guides and Tutorials" price="10.90">
            <medium id="4">
                <mediumType>DVD</mediumType>
                <name>Photoshop CS6 Tutorial Training</name>
                <length>1200</length>
                <status>available</status>
                <releaseYear>2015</releaseYear>
            </medium>
            <medium id="5">
                <mediumType>DVD</mediumType>
                <name>Dance Lessons 101: The Basics and Beyond!</name>
                <length>unknown</length>
                <status>rented</status>
                <releaseYear>2012</releaseYear>
            </medium>
        </category>
    </categories>
</videoLibrary>
